### ISSUE TITLE
FR: App on f-droid

### ISSUE THREAD

**Issue by mueller-ma** [ekahlenberger/HomeAutomationAlarmSender#1]
Hey,
I would like to see this app f-droid, an foss app store for android. Its easier to distribute (for people using fdroid) than downloading from github. I can do the config for f-droid for you (in their repo).
All you have to do is to tag a new version, f-droid builds, signs and distribute the app theirself.

It would be nice if you could add metadata to this repo like https://github.com/openhab/openhab-android/tree/master/fastlane/metadata/android/en-US

**Comment by ekahlenberger** [comment]
I like that idea, but I'm a bit lost here. Do you have a guide for me? Should I just use a release tag containing "fdroid"? Meanwhile I'm searching for a guide by myself and setup notifications for github issues ^^....

Thanks a lot

**Comment by ekahlenberger** [comment]
I pushed some metadata to this repository...

**Comment by mueller-ma** [comment]
[Here](https://github.com/settings/notifications) you can select "Automatically watch repositories" and watch this repo manually, so you will always receive notifications.

You don't need extra fdroid tags (we do this in openhab-android, but the situation there is much more complex). The name of the tag should be the version name used in the manifest.

**Comment by mueller-ma** [comment]
Can you add the gradle hashsum? See https://gitlab.com/fdroid/rfp/issues/538#note_66945252

**Comment by mueller-ma** [comment]
The official openHAB app also had a feature graphic with transparent background which doesn't look nice.

**Comment by ekahlenberger** [comment]
I pushed both changes. Do I have to create another release for fdroid to pull the changes?

**Comment by mueller-ma** [comment]
@ekahlenberger Yes, you should. Otherwise F-Droid cannot use the updated metadata.
