### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by dave01945** [ekahlenberger/HomeAutomationAlarmSender#8]
I can't get the app to work.
After filling in the details for the rest interface I get the error 

No Protocol: openhab.home/rest/items/AndroidAlarm1/state

Can you help with what is wrong?

Thanks

**Comment by ekahlenberger** [comment]
My first guess ist, that you did not install the REST interface for your openhab server. If you did set it up, check if the given URL (http://openhab.home/rest/items/AndroidAlarm1/state) is reachable via browser on your phone or local computer (assuming they are both in the same network as your openhab server).

**Comment by dave01945** [comment]
Thanks I figured out my problem.
I needed to enter http:// in the server section as it doesn't work without it.

**Comment by ekahlenberger** [comment]
thanks for the feedback, should change that
